
# ENABLE TERMINAL COLORS
[env]
TERM = "xterm-256color"


# WINDOW PADDING
[window]
padding.x = 10
padding.y = 10

# WINDOW BUTTONS
#decorations = "Buttonless"

# WINDOW SPAWNING
[keyboard]
bindings = [{ key = "n", mods = "Control|Shift", action = "CreateNewWindow" }]

# TRANSPARENCY
opacity = 0.8
#transparent_background_colors = true

# BLUR
# blur = true


# FONT CONFIGS
[font]
size = 14.0

[font.bold]
# family = "Hack Nerd Font Mono"
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
# family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "Hack Nerd Font Mono"
family = "Hack Nerd Font"
style = "Regular"

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

