name: stale
on:
  schedule:
    - cron: "12 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          enable-statistics: true
          ascending: true
          days-before-issue-stale: 60
          days-before-issue-close: -1
          stale-issue-message: "Issue has been marked as stale due to no activity"
          stale-issue-label: "stale"

          days-before-pr-stale: 60
          days-before-pr-close: -1
          stale-pr-message: "Pull Request has been marked as stale due to no activity"
          stale-pr-label: "stale"
